// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uwpUI.Core.Data;

namespace uwpUI.Core.Migrations
{
    [DbContext(typeof(BdoContext))]
    [Migration("20190811023451_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("uwpUI.Core.Models.BdoItem", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("BuyPrice");

                    b.Property<string>("Category")
                        .HasMaxLength(25);

                    b.Property<string>("Description");

                    b.Property<int>("Grade");

                    b.Property<string>("Img")
                        .HasMaxLength(100);

                    b.Property<int?>("ItemGroupId");

                    b.Property<string>("Knowledge");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("SellPrice");

                    b.Property<string>("Weight")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("uwpUI.Core.Models.ItemGroup", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("ItemGroups");
                });

            modelBuilder.Entity("uwpUI.Core.Models.Recipe", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("Exp");

                    b.Property<int>("Grade");

                    b.Property<string>("Img");

                    b.Property<int?>("Item1Id");

                    b.Property<int?>("Item2Id");

                    b.Property<string>("Name");

                    b.Property<string>("SkillLevel");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Item1Id");

                    b.HasIndex("Item2Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("uwpUI.Core.Models.RecipeMat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<bool>("IsItem");

                    b.Property<int?>("ItemGroupId");

                    b.Property<int?>("ItemId");

                    b.Property<int>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeMats");
                });

            modelBuilder.Entity("uwpUI.Core.Models.BdoItem", b =>
                {
                    b.HasOne("uwpUI.Core.Models.ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId");
                });

            modelBuilder.Entity("uwpUI.Core.Models.Recipe", b =>
                {
                    b.HasOne("uwpUI.Core.Models.BdoItem", "Item1")
                        .WithMany()
                        .HasForeignKey("Item1Id");

                    b.HasOne("uwpUI.Core.Models.BdoItem", "Item2")
                        .WithMany()
                        .HasForeignKey("Item2Id");
                });

            modelBuilder.Entity("uwpUI.Core.Models.RecipeMat", b =>
                {
                    b.HasOne("uwpUI.Core.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId");

                    b.HasOne("uwpUI.Core.Models.BdoItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("uwpUI.Core.Models.Recipe")
                        .WithMany("Mats")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
